# Generated by Django 5.2.7 on 2025-10-31 20:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pobox', models.IntegerField(blank=True, null=True)),
                ('strasse', models.CharField(blank=True, max_length=100, null=True)),
                ('plz', models.CharField(blank=True, max_length=20, null=True)),
                ('ort', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anrede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(max_length=100)),
                ('oldid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beruf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beruf', models.CharField(max_length=100)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('oldid', models.IntegerField()),
            ],
            options={
                'ordering': ['beruf'],
            },
        ),
        migrations.CreateModel(
            name='Kosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(max_length=3)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('betrag', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'ordering': ['art'],
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.CharField(max_length=100)),
                ('iso', models.CharField(max_length=4)),
                ('EU', models.BooleanField(default=True)),
                ('oldid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mitgliedsart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitart', models.CharField(max_length=3)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('anmerkung', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['mitart'],
            },
        ),
        migrations.CreateModel(
            name='Titel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('oldid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Versand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versand', models.CharField(max_length=3)),
                ('bezeichnung', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vortragold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldid', models.IntegerField()),
                ('Vortragsort', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vortragsort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vortragsort', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AboHeft',
            fields=[
                ('adresse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mitglieder.adresse')),
                ('abonummer', models.IntegerField()),
                ('anrede', models.CharField(blank=True, max_length=100, null=True)),
                ('titel', models.CharField(blank=True, max_length=100, null=True)),
                ('vorname', models.CharField(blank=True, max_length=100, null=True)),
                ('nachname', models.CharField(blank=True, max_length=100, null=True)),
                ('surname2', models.CharField(blank=True, max_length=100, null=True)),
                ('surname3', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('heftanzahl', models.IntegerField(default=0)),
                ('beigz', models.CharField(blank=True, max_length=20, null=True)),
                ('beidat', models.DateField(blank=True, null=True)),
                ('storndat', models.DateField(blank=True, null=True)),
                ('rueckstand', models.FloatField(default=0.0)),
                ('gutschrift', models.FloatField(default=0.0)),
                ('aboart', models.CharField(choices=[('DA', 'Dauerauftrag'), ('JB', 'Jahresbestellung')], default='DA', max_length=2)),
                ('aboanfang', models.DateField(blank=True, null=True)),
                ('aboende', models.DateField(blank=True, null=True)),
                ('anmerkung', models.TextField(blank=True, null=True)),
                ('rechnung', models.FileField(blank=True, upload_to='invoices/')),
            ],
            bases=('mitglieder.adresse',),
        ),
        migrations.CreateModel(
            name='Abonnent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kundennummer', models.IntegerField()),
                ('titel', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('name2', models.CharField(blank=True, max_length=100, null=True)),
                ('name3', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('uid', models.CharField(blank=True, max_length=20, null=True)),
                ('prozent', models.FloatField(default=0.0)),
                ('rechnungsanzahl', models.IntegerField(default=0)),
                ('dsgvo', models.BooleanField(default=False, help_text='Mitglied hat zur Datenschutzgrundverordnung zugestimmt.', verbose_name='Datenschutzgrundverordnung')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('rechnung', models.FileField(blank=True, upload_to='aboinvoices/')),
                ('rechnungsanschrift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Anschrift', to='mitglieder.adresse')),
            ],
        ),
        migrations.AddField(
            model_name='adresse',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.land'),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitgliedsnummer', models.IntegerField()),
                ('institution_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name2', models.CharField(blank=True, max_length=100, null=True)),
                ('name3', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage', models.CharField(blank=True, max_length=100, null=True)),
                ('beigz', models.CharField(blank=True, max_length=20, null=True)),
                ('beidat', models.DateField(blank=True, null=True)),
                ('storndat', models.DateField(blank=True, null=True)),
                ('versand', models.CharField(blank=True, max_length=20, null=True)),
                ('sub', models.CharField(blank=True, max_length=10, null=True)),
                ('heftanzahl', models.IntegerField(default=0)),
                ('anmerkung', models.TextField(blank=True, null=True)),
                ('rechnung', models.FileField(blank=True, upload_to='invoices/')),
                ('dsgvo', models.BooleanField(default=False, help_text='Mitglied hat zur Datenschutzgrundverordnung zugestimmt.', verbose_name='Datenschutzgrundverordnung')),
                ('berufsgruppe', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.beruf')),
                ('lieferadresse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Zustelladresse2', to='mitglieder.adresse')),
                ('rechnungsadresse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rechnungsadresse2', to='mitglieder.adresse')),
                ('wohnadresse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Wohnadresse2', to='mitglieder.adresse')),
                ('kostenart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.kosten')),
                ('mitgliedsart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.mitgliedsart')),
                ('vortrag', models.ManyToManyField(to='mitglieder.vortragsort')),
            ],
        ),
        migrations.CreateModel(
            name='PasswortLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkvalue', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vereins_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VereinsMitglied',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mitgliedsnummer', models.IntegerField(editable=False)),
                ('anrede', models.CharField(blank=True, max_length=100, null=True)),
                ('titel', models.CharField(blank=True, max_length=100, null=True)),
                ('namenszusatz', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('beigz', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('beidat', models.DateField(blank=True, null=True)),
                ('storndat', models.DateField(blank=True, null=True)),
                ('versand', models.CharField(blank=True, max_length=20, null=True)),
                ('gebdat', models.DateField(blank=True, null=True)),
                ('diplomdat', models.DateField(blank=True, null=True)),
                ('diplomort', models.CharField(blank=True, max_length=100, null=True)),
                ('sub', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('vortragold', models.CharField(blank=True, max_length=10, null=True)),
                ('heftanzahl', models.IntegerField(default=0)),
                ('anmerkung', models.TextField(blank=True, null=True)),
                ('dsgvo', models.BooleanField(default=False, help_text='Mitglied hat zur Datenschutzgrundverordnung zugestimmt.', verbose_name='Datenschutzgrundverordnung')),
                ('rechnung', models.FileField(blank=True, upload_to='invoices/')),
                ('berufsgruppe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.beruf')),
                ('kostenart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.kosten')),
                ('lieferadresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Zustelladresse', to='mitglieder.adresse')),
                ('mitgliedsart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.mitgliedsart')),
                ('rechnungsadresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rechnungsadresse', to='mitglieder.adresse')),
                ('wohnadresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Wohnadresse', to='mitglieder.adresse')),
                ('vortrag', models.ManyToManyField(blank=True, to='mitglieder.vortragsort')),
            ],
            options={
                'ordering': ['last_name'],
            },
            bases=('auth.user',),
        ),
        migrations.CreateModel(
            name='offenePosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bezahltam', models.DateTimeField(blank=True, null=True)),
                ('offen', models.FloatField(default=0)),
                ('zahlung', models.FloatField(blank=True, default=0, null=True)),
                ('bezahlt', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.institution')),
                ('mitglied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.vereinsmitglied')),
            ],
            options={
                'ordering': ['erstellt'],
            },
        ),
        migrations.CreateModel(
            name='EmailId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid4', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bezahltam', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('offeneposten', models.ManyToManyField(to='mitglieder.offeneposten')),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitglieder.vereinsmitglied')),
            ],
        ),
        migrations.CreateModel(
            name='offeneAboPosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bezahltam', models.DateTimeField(blank=True, null=True)),
                ('offen', models.FloatField(default=0)),
                ('zahlung', models.FloatField(blank=True, default=0, null=True)),
                ('bezahlt', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('aboheft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.aboheft')),
            ],
            options={
                'ordering': ['erstellt'],
            },
        ),
        migrations.AddField(
            model_name='aboheft',
            name='kundennummer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.abonnent'),
        ),
    ]
